parameters:
    summercamp.rest.controller.class: EzSystems\SummerCamp2013RestApiBundle\Controller\RestController

services:
    summercamp.rest.controller:
        class: %summercamp.rest.controller.class%
        calls:
            - [ setContainer, [@service_container] ]
